version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "{{.db.name}}"
      POSTGRES_USER: "{{.db.user}}"
      POSTGRES_PASSWORD: "{{.db.password}}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - {{.username}}/{{.db.name}}:/var/lib/postgresql/data
    ports:
      - "{{.port}}:5432"